"""add options quotes table

Revision ID: 7074ef78558b
Revises: 
Create Date: 2021-06-13 19:38:50.960690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7074ef78558b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options_quotes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('type', sa.Enum('C', 'P', name='optiontypes'), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('bid_price', sa.Numeric(precision=2), nullable=True),
    sa.Column('bid_size', sa.Integer(), nullable=True),
    sa.Column('ask_price', sa.Numeric(precision=2), nullable=True),
    sa.Column('ask_size', sa.Integer(), nullable=True),
    sa.Column('last_trade_price_tr_hrs', sa.Numeric(precision=2), nullable=True),
    sa.Column('last_trade_price', sa.Numeric(precision=2), nullable=True),
    sa.Column('last_trade_size', sa.Integer(), nullable=True),
    sa.Column('last_trade_tick', sa.String(length=10), nullable=True),
    sa.Column('last_trade_time', sa.DateTime(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_price', sa.Numeric(precision=2), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=2), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=2), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=6), nullable=True),
    sa.Column('delta', sa.Numeric(precision=6), nullable=True),
    sa.Column('gamma', sa.Numeric(precision=6), nullable=True),
    sa.Column('theta', sa.Numeric(precision=6), nullable=True),
    sa.Column('vega', sa.Numeric(precision=6), nullable=True),
    sa.Column('rho', sa.Numeric(precision=6), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.Column('is_halted', sa.Boolean(), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=2), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_id'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('options_quotes')
    # ### end Alembic commands ###
