Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.

Resources:
  brokerRetrievalGrantAccessEFS:
    Metadata:
      'aws:copilot:description': 'An IAM ManagedPolicy for your service to mount and write to EFS.'
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Grants write and mount access to EFS
      PolicyDocument:
        Version: 2012-10-17
        Statement:
            Effect: Allow
            Action:
              - 'elasticfilesystem:ClientMount'
              - 'elasticfilesystem:ClientWrite'
            Resource: "*"
Outputs:
  brokerRetrievalGrantAccessEFS:
    Description: "The IAM::ManagedPolicy to attach to the task role"
    Value: !Ref brokerRetrievalGrantAccessEFS